/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.10.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.standofit.back.api.execution;

import com.standofit.back.api.execution.dto.AddExerciseLogRequest;
import com.standofit.back.api.execution.dto.ExerciseLogDTO;
import com.standofit.back.api.execution.dto.ResponseDTO;
import com.standofit.back.api.execution.dto.SessionDTO;
import com.standofit.back.api.execution.dto.SessionListDTO;
import com.standofit.back.api.execution.dto.StartSessionRequest;
import java.net.URI;
import java.util.UUID;
import com.standofit.back.api.execution.dto.UpdateNotesRequest;
import com.standofit.back.api.execution.dto.UpdateRepsRequest;
import com.standofit.back.api.execution.dto.UpdateSetsRequest;
import com.standofit.back.api.execution.dto.UpdateWeightRequest;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2026-04-27T13:35:26.515198142+02:00[Europe/Madrid]", comments = "Generator version: 7.10.0")
@Validated
@Tag(name = "Exercise Logs", description = "the Exercise Logs API")
public interface ApiApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * POST /api/sessions/{sessionId}/logs : Añadir ejercicio a la sesión
     *
     * @param sessionId  (required)
     * @param addExerciseLogRequest  (required)
     * @return Ejercicio añadido (status code 201)
     *         or Sesión no encontrada (status code 404)
     */
    @Operation(
        operationId = "addExerciseLog",
        summary = "Añadir ejercicio a la sesión",
        tags = { "Exercise Logs" },
        responses = {
            @ApiResponse(responseCode = "201", description = "Ejercicio añadido"),
            @ApiResponse(responseCode = "404", description = "Sesión no encontrada", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ResponseDTO.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/api/sessions/{sessionId}/logs",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    default ResponseEntity<Void> addExerciseLog(
        @Parameter(name = "sessionId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("sessionId") UUID sessionId,
        @Parameter(name = "AddExerciseLogRequest", description = "", required = true) @Valid @RequestBody AddExerciseLogRequest addExerciseLogRequest
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"payload\" : \"{}\", \"error\" : { \"code\" : \"code\", \"message\" : \"message\", \"timestamp\" : \"2000-01-23T04:56:07.000+00:00\" } }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * POST /api/sessions/{sessionId}/cancel : Cancelar sesión
     *
     * @param sessionId  (required)
     * @return Sesión cancelada (status code 204)
     *         or Sesión no encontrada (status code 404)
     */
    @Operation(
        operationId = "cancelSession",
        summary = "Cancelar sesión",
        tags = { "Sessions" },
        responses = {
            @ApiResponse(responseCode = "204", description = "Sesión cancelada"),
            @ApiResponse(responseCode = "404", description = "Sesión no encontrada", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ResponseDTO.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/api/sessions/{sessionId}/cancel",
        produces = { "application/json" }
    )
    
    default ResponseEntity<Void> cancelSession(
        @Parameter(name = "sessionId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("sessionId") UUID sessionId
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"payload\" : \"{}\", \"error\" : { \"code\" : \"code\", \"message\" : \"message\", \"timestamp\" : \"2000-01-23T04:56:07.000+00:00\" } }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * DELETE /api/sessions/{sessionId} : Eliminar sesión
     *
     * @param sessionId  (required)
     * @return Sesión eliminada (status code 204)
     */
    @Operation(
        operationId = "deleteSession",
        summary = "Eliminar sesión",
        tags = { "Sessions" },
        responses = {
            @ApiResponse(responseCode = "204", description = "Sesión eliminada")
        }
    )
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = "/api/sessions/{sessionId}"
    )
    
    default ResponseEntity<Void> deleteSession(
        @Parameter(name = "sessionId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("sessionId") UUID sessionId
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * POST /api/sessions/{sessionId}/finish : Finalizar sesión
     *
     * @param sessionId  (required)
     * @return Sesión finalizada (status code 204)
     *         or Sesión no encontrada (status code 404)
     */
    @Operation(
        operationId = "finishSession",
        summary = "Finalizar sesión",
        tags = { "Sessions" },
        responses = {
            @ApiResponse(responseCode = "204", description = "Sesión finalizada"),
            @ApiResponse(responseCode = "404", description = "Sesión no encontrada", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ResponseDTO.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/api/sessions/{sessionId}/finish",
        produces = { "application/json" }
    )
    
    default ResponseEntity<Void> finishSession(
        @Parameter(name = "sessionId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("sessionId") UUID sessionId
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"payload\" : \"{}\", \"error\" : { \"code\" : \"code\", \"message\" : \"message\", \"timestamp\" : \"2000-01-23T04:56:07.000+00:00\" } }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * GET /api/sessions : Listar todas las sesiones
     *
     * @return Lista de sesiones (status code 200)
     *         or No hay sesiones (status code 204)
     *         or Error (status code 400)
     */
    @Operation(
        operationId = "getAllSessions",
        summary = "Listar todas las sesiones",
        tags = { "Sessions" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Lista de sesiones", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = SessionListDTO.class))
            }),
            @ApiResponse(responseCode = "204", description = "No hay sesiones"),
            @ApiResponse(responseCode = "400", description = "Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ResponseDTO.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/api/sessions",
        produces = { "application/json" }
    )
    
    default ResponseEntity<SessionListDTO> getAllSessions(
        
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"sessions\" : [ { \"createdAt\" : \"2000-01-23T04:56:07.000+00:00\", \"notes\" : \"notes\", \"dayId\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"id\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"status\" : \"IN_PROGRESS\", \"updatedAt\" : \"2000-01-23T04:56:07.000+00:00\" }, { \"createdAt\" : \"2000-01-23T04:56:07.000+00:00\", \"notes\" : \"notes\", \"dayId\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"id\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"status\" : \"IN_PROGRESS\", \"updatedAt\" : \"2000-01-23T04:56:07.000+00:00\" } ] }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"payload\" : \"{}\", \"error\" : { \"code\" : \"code\", \"message\" : \"message\", \"timestamp\" : \"2000-01-23T04:56:07.000+00:00\" } }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * GET /api/sessions/{sessionId}/logs : Listar ejercicios de una sesión
     *
     * @param sessionId  (required)
     * @return Lista de ejercicios (status code 200)
     *         or No hay ejercicios (status code 204)
     *         or Sesión no encontrada (status code 404)
     */
    @Operation(
        operationId = "getExerciseLogs",
        summary = "Listar ejercicios de una sesión",
        tags = { "Exercise Logs" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Lista de ejercicios", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = ExerciseLogDTO.class)))
            }),
            @ApiResponse(responseCode = "204", description = "No hay ejercicios"),
            @ApiResponse(responseCode = "404", description = "Sesión no encontrada", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ResponseDTO.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/api/sessions/{sessionId}/logs",
        produces = { "application/json" }
    )
    
    default ResponseEntity<List<ExerciseLogDTO>> getExerciseLogs(
        @Parameter(name = "sessionId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("sessionId") UUID sessionId
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "[ { \"reps\" : 6, \"exerciseId\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"sets\" : 0, \"weight\" : 1, \"id\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\" }, { \"reps\" : 6, \"exerciseId\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"sets\" : 0, \"weight\" : 1, \"id\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\" } ]";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"payload\" : \"{}\", \"error\" : { \"code\" : \"code\", \"message\" : \"message\", \"timestamp\" : \"2000-01-23T04:56:07.000+00:00\" } }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * GET /api/sessions/{sessionId} : Obtener sesión por ID
     *
     * @param sessionId  (required)
     * @return Sesión encontrada (status code 200)
     *         or Sesión no encontrada (status code 404)
     */
    @Operation(
        operationId = "getSessionById",
        summary = "Obtener sesión por ID",
        tags = { "Sessions" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Sesión encontrada", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = SessionDTO.class))
            }),
            @ApiResponse(responseCode = "404", description = "Sesión no encontrada", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ResponseDTO.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/api/sessions/{sessionId}",
        produces = { "application/json" }
    )
    
    default ResponseEntity<SessionDTO> getSessionById(
        @Parameter(name = "sessionId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("sessionId") UUID sessionId
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"createdAt\" : \"2000-01-23T04:56:07.000+00:00\", \"notes\" : \"notes\", \"dayId\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"id\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"status\" : \"IN_PROGRESS\", \"updatedAt\" : \"2000-01-23T04:56:07.000+00:00\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"payload\" : \"{}\", \"error\" : { \"code\" : \"code\", \"message\" : \"message\", \"timestamp\" : \"2000-01-23T04:56:07.000+00:00\" } }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * DELETE /api/sessions/{sessionId}/logs/{logId} : Eliminar ejercicio de la sesión
     *
     * @param sessionId  (required)
     * @param logId  (required)
     * @return Ejercicio eliminado (status code 204)
     *         or Sesión o ejercicio no encontrado (status code 404)
     */
    @Operation(
        operationId = "removeExerciseLog",
        summary = "Eliminar ejercicio de la sesión",
        tags = { "Exercise Logs" },
        responses = {
            @ApiResponse(responseCode = "204", description = "Ejercicio eliminado"),
            @ApiResponse(responseCode = "404", description = "Sesión o ejercicio no encontrado", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ResponseDTO.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = "/api/sessions/{sessionId}/logs/{logId}",
        produces = { "application/json" }
    )
    
    default ResponseEntity<Void> removeExerciseLog(
        @Parameter(name = "sessionId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("sessionId") UUID sessionId,
        @Parameter(name = "logId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("logId") UUID logId
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"payload\" : \"{}\", \"error\" : { \"code\" : \"code\", \"message\" : \"message\", \"timestamp\" : \"2000-01-23T04:56:07.000+00:00\" } }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * POST /api/sessions : Iniciar una nueva sesión
     *
     * @param startSessionRequest  (required)
     * @return Sesión creada (status code 201)
     */
    @Operation(
        operationId = "startSession",
        summary = "Iniciar una nueva sesión",
        tags = { "Sessions" },
        responses = {
            @ApiResponse(responseCode = "201", description = "Sesión creada")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/api/sessions",
        consumes = { "application/json" }
    )
    
    default ResponseEntity<Void> startSession(
        @Parameter(name = "StartSessionRequest", description = "", required = true) @Valid @RequestBody StartSessionRequest startSessionRequest
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * PATCH /api/sessions/{sessionId}/logs/{logId}/reps : Actualizar repeticiones de un ejercicio
     *
     * @param sessionId  (required)
     * @param logId  (required)
     * @param updateRepsRequest  (required)
     * @return Repeticiones actualizadas (status code 204)
     *         or Sesión o ejercicio no encontrado (status code 404)
     */
    @Operation(
        operationId = "updateExerciseLogReps",
        summary = "Actualizar repeticiones de un ejercicio",
        tags = { "Exercise Logs" },
        responses = {
            @ApiResponse(responseCode = "204", description = "Repeticiones actualizadas"),
            @ApiResponse(responseCode = "404", description = "Sesión o ejercicio no encontrado", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ResponseDTO.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.PATCH,
        value = "/api/sessions/{sessionId}/logs/{logId}/reps",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    default ResponseEntity<Void> updateExerciseLogReps(
        @Parameter(name = "sessionId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("sessionId") UUID sessionId,
        @Parameter(name = "logId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("logId") UUID logId,
        @Parameter(name = "UpdateRepsRequest", description = "", required = true) @Valid @RequestBody UpdateRepsRequest updateRepsRequest
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"payload\" : \"{}\", \"error\" : { \"code\" : \"code\", \"message\" : \"message\", \"timestamp\" : \"2000-01-23T04:56:07.000+00:00\" } }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * PATCH /api/sessions/{sessionId}/logs/{logId}/sets : Actualizar series de un ejercicio
     *
     * @param sessionId  (required)
     * @param logId  (required)
     * @param updateSetsRequest  (required)
     * @return Series actualizadas (status code 204)
     *         or Sesión o ejercicio no encontrado (status code 404)
     */
    @Operation(
        operationId = "updateExerciseLogSets",
        summary = "Actualizar series de un ejercicio",
        tags = { "Exercise Logs" },
        responses = {
            @ApiResponse(responseCode = "204", description = "Series actualizadas"),
            @ApiResponse(responseCode = "404", description = "Sesión o ejercicio no encontrado", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ResponseDTO.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.PATCH,
        value = "/api/sessions/{sessionId}/logs/{logId}/sets",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    default ResponseEntity<Void> updateExerciseLogSets(
        @Parameter(name = "sessionId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("sessionId") UUID sessionId,
        @Parameter(name = "logId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("logId") UUID logId,
        @Parameter(name = "UpdateSetsRequest", description = "", required = true) @Valid @RequestBody UpdateSetsRequest updateSetsRequest
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"payload\" : \"{}\", \"error\" : { \"code\" : \"code\", \"message\" : \"message\", \"timestamp\" : \"2000-01-23T04:56:07.000+00:00\" } }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * PATCH /api/sessions/{sessionId}/logs/{logId}/weight : Actualizar peso de un ejercicio
     *
     * @param sessionId  (required)
     * @param logId  (required)
     * @param updateWeightRequest  (required)
     * @return Peso actualizado (status code 204)
     *         or Sesión o ejercicio no encontrado (status code 404)
     */
    @Operation(
        operationId = "updateExerciseLogWeight",
        summary = "Actualizar peso de un ejercicio",
        tags = { "Exercise Logs" },
        responses = {
            @ApiResponse(responseCode = "204", description = "Peso actualizado"),
            @ApiResponse(responseCode = "404", description = "Sesión o ejercicio no encontrado", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ResponseDTO.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.PATCH,
        value = "/api/sessions/{sessionId}/logs/{logId}/weight",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    default ResponseEntity<Void> updateExerciseLogWeight(
        @Parameter(name = "sessionId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("sessionId") UUID sessionId,
        @Parameter(name = "logId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("logId") UUID logId,
        @Parameter(name = "UpdateWeightRequest", description = "", required = true) @Valid @RequestBody UpdateWeightRequest updateWeightRequest
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"payload\" : \"{}\", \"error\" : { \"code\" : \"code\", \"message\" : \"message\", \"timestamp\" : \"2000-01-23T04:56:07.000+00:00\" } }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * PUT /api/sessions/{sessionId}/notes : Actualizar notas de la sesión
     *
     * @param sessionId  (required)
     * @param updateNotesRequest  (required)
     * @return Notas actualizadas (status code 204)
     *         or Sesión no encontrada (status code 404)
     */
    @Operation(
        operationId = "updateSessionNotes",
        summary = "Actualizar notas de la sesión",
        tags = { "Sessions" },
        responses = {
            @ApiResponse(responseCode = "204", description = "Notas actualizadas"),
            @ApiResponse(responseCode = "404", description = "Sesión no encontrada", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ResponseDTO.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = "/api/sessions/{sessionId}/notes",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    default ResponseEntity<Void> updateSessionNotes(
        @Parameter(name = "sessionId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("sessionId") UUID sessionId,
        @Parameter(name = "UpdateNotesRequest", description = "", required = true) @Valid @RequestBody UpdateNotesRequest updateNotesRequest
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"payload\" : \"{}\", \"error\" : { \"code\" : \"code\", \"message\" : \"message\", \"timestamp\" : \"2000-01-23T04:56:07.000+00:00\" } }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
